# Generated by Django 4.1.3 on 2022-11-06 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(blank=True, db_column='USER_ID', null=True)),
                ('title', models.CharField(blank=True, db_column='title', max_length=50, null=True)),
                ('body', models.CharField(blank=True, db_column='description', max_length=100, null=True)),
            ],
            options={
                'db_table': 'user_table',
                'managed': True,
            },
        ),
    ]
