# Generated by Django 4.1.3 on 2022-11-07 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financepeer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='body',
            field=models.CharField(blank=True, db_column='description', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='title',
            field=models.CharField(blank=True, db_column='title', max_length=200, null=True),
        ),
    ]
